trigger:
  branches:
    include:
      - main

# Define pipeline variables
variables:
  TF_VERSION: '1.5.0'  # Specify your required Terraform version
  PROVIDER_CITRIX_VERSION: '~> 1.0.0'  # Ensure compatibility with the Citrix Terraform provider

stages:
  - stage: TerraformInit
    displayName: 'Terraform Init Stage'
    jobs:
      - job: InitTerraform
        displayName: 'Initialize Terraform'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: $(TF_VERSION)

          - task: DownloadSecureFile@1
            name: 'citrixCredentials'
            inputs:
              secureFile: 'citrix_api_key.json'  # Assuming you have stored credentials securely

          - checkout: self
          
          # Backend configuration (Azure Storage for state management)
          - script: |
              terraform init \
              -backend-config="storage_account_name=$(AZURE_STORAGE_ACCOUNT)" \
              -backend-config="container_name=$(TF_STATE_CONTAINER)" \
              -backend-config="key=$(TF_STATE_KEY)" \
              -backend-config="access_key=$(AZURE_STORAGE_ACCESS_KEY)"
            displayName: 'Terraform Init with Backend'

  - stage: TerraformPlan
    displayName: 'Terraform Plan Stage'
    dependsOn: TerraformInit
    jobs:
      - job: PlanTerraform
        displayName: 'Terraform Plan'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: $(TF_VERSION)

          - script: |
              terraform plan \
              -var "citrix_api_key=$(citrixCredentials.citrix_api_key)" \
              -var "citrix_api_url=$(CITRIX_API_URL)"
            displayName: 'Terraform Plan'

  - stage: TerraformApply
    displayName: 'Terraform Apply Stage'
    dependsOn: TerraformPlan
    jobs:
      - job: ApplyTerraform
        displayName: 'Apply Terraform Changes'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: $(TF_VERSION)

          - script: |
              terraform apply -auto-approve \
              -var "citrix_api_key=$(citrixCredentials.citrix_api_key)" \
              -var "citrix_api_url=$(CITRIX_API_URL)"
            displayName: 'Apply Terraform'
